name: daily-job
on:
  schedule:
    - cron: '30 8 * * *'   # 08:30
  workflow_dispatch:
permissions:
  actions: write
  contents: read
jobs:
  task:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
      - name: setting timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Find all images to build
        run: go run main.go -daily_job

      - name: invoke build-manually pipeline
        run: |
          while read -r tag; do
            echo "Triggering build for $tag"
            curl -s -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/$REPO/actions/workflows/build-manually.yml/dispatches \
              -d "{\"ref\":\"main\",\"inputs\":{\"tag\":\"$tag\"}}"
          done < /tmp/daily-job.txt